#! usr/bin/env php
<?php

namespace Structural\FluentInterface;

require_once 'vendor/autoload.php';

$class = new SomeClass();
$class->setFirstValue(123)->setSecondValue(456)->setThirdValue(789);

printf("%s\n", $class->aggregate());
